### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1559]
```
failures:

---- metrics::tests::second_delta_export_does_not_give_no_attr_value_if_add_not_called stdout ----
thread 'metrics::tests::second_delta_export_does_not_give_no_attr_value_if_add_not_called' panicked at opentelemetry-sdk/src/metrics/mod.rs:674:13:
No scope metrics in latest export
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    metrics::tests::second_delta_export_does_not_give_no_attr_value_if_add_not_called
```

**Comment by cijothomas** [comment]
failures:

---- metrics::tests::second_delta_export_does_not_give_no_attr_value_if_add_not_called stdout ----
thread 'metrics::tests::second_delta_export_does_not_give_no_attr_value_if_add_not_called' panicked at opentelemetry-sdk/src/metrics/mod.rs:674:13:
No scope metrics in latest export
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    metrics::tests::second_delta_export_does_not_give_no_attr_value_if_add_not_called

test result: FAILED. 116 passed; 1 failed; 7 ignored; 0 measured; 0 filtered out; finished in 2.01s

error: test failed, to rerun pass `-p opentelemetry_sdk --lib`
