### ISSUE TITLE
[Bug]: Flacky test for default Span's batch

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/opentelemetry-rust#1652]
### What happened?

Flaky test when running with `RUST_BACKTRACE=1 cargo test -p opentelemetry_sdk --lib`:

```
---- trace::span_processor::tests::test_default_batch_config_adheres_to_specificatio
n stdout ----
thread 'trace::span_processor::tests::test_default_batch_config_adheres_to_specifica
tion' panicked at opentelemetry-sdk/src/trace/span_processor.rs:754:9:
assertion `left == right` failed
  left: 2.046s
 right: 30s
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/pani
cking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/pan
icking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/pan
icking.rs:342:17
   3: core::panicking::assert_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/pan
icking.rs:297:5
   4: opentelemetry_sdk::trace::span_processor::tests::test_default_batch_config_adh
eres_to_specification
             at ./src/trace/span_processor.rs:754:9
   5: opentelemetry_sdk::trace::span_processor::tests::test_default_batch_config_adh
eres_to_specification::{{closure}}
             at ./src/trace/span_processor.rs:747:60
   6: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops
/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops
/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtra
ce.


failures:
    trace::span_processor::tests::test_default_batch_config_adheres_to_specification

test result: FAILED. 116 passed; 1 failed; 7 ignored; 0 measured; 0 filtered out; fi
nished in 2.01s
```

### API Version

v0.19

### SDK Version

v0.22.1

**Comment by rogercoll** [comment]
The test seems to collide with https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/trace/span_processor.rs#L824
