### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vincenzopalazzo** [open-telemetry/opentelemetry-rust#2157]
### What happened?

While upgrading my open telemetry library to the 0.25 version (See the diff here) I get the following error

```
thread 'main' panicked at opentelemetry-common/src/lib.rs:42:9:
Failed to shutdown logger: Other("[ExportFailed(Status { code: Unknown, message: \", detailed error message: h2 protocol error: http2 error tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: GoAway(b\\\"\\\", FRAME_SIZE_ERROR, Library) }))\" })]")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### API Version

No idea, I use https://github.com/grafana/docker-otel-lgtm

### SDK Version

0.25

### What Exporter(s) are you seeing the problem on?

OTLP

### Relevant log output

```shell
thread 'main' panicked at opentelemetry-common/src/lib.rs:42:9:
Failed to shutdown logger: Other("[ExportFailed(Status { code: Unknown, message: \", detailed error message: h2 protocol error: http2 error tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: GoAway(b\\\"\\\", FRAME_SIZE_ERROR, Library) }))\" })]")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```

**Comment by lalitb** [comment]
I see that you have switched from the otlp-http to otlp-grpc, along with  0.25 . Can you check if the issue happens with otlp-http too?

**Comment by vincenzopalazzo** [comment]
>I see that you have switched from the otlp-http to otlp-grpc, along with 0.25 . Can you check if the issue happens with otlp-http too?

Do you mean that with the 0.24 the grpc is by default? and I should use a setting like https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-otlp/examples/basic-otlp-http/src/main.rs
