### ISSUE TITLE
Cannot make datadog + `tracing-opentelemetry` work

### ISSUE THREAD

**Issue by little-dude** [open-telemetry/opentelemetry-rust#492]
Hello, and thank you for these libraries :)

I have a program that uses `tracing`, and I need to integrate with datadog. I think it should be possible to use `tracing-opentelemetry` along with the `opentelemetry_contrib::trace::exporter::datadog` exporter but:

- I don't see any trace in datadog
- I have a crash

A small reproducible example can be found at https://github.com/little-dude/testdatadog

Here is the code:

```rust
#[macro_use]
extern crate tracing;

use opentelemetry_contrib::trace::exporter::datadog;
use tracing_subscriber::layer::SubscriberExt;

#[tokio::main]
async fn main() {
    create_datadog_tracing_subscriber("http://localhost:8126");
    error!("error");
    warn!("warn");
    info!("info");
    debug!("debug");
    trace!("trace");
    tokio::time::sleep(std::time::Duration::from_millis(1_000)).await;
}

fn create_datadog_tracing_subscriber(agent: &str) {
    let (tracer, uninstall) = datadog::new_pipeline()
        .with_service_name("datadogtest")
        .with_version(datadog::ApiVersion::Version05)
        .with_agent_endpoint(agent)
        .install()
        .unwrap();

    // Never drop `uninstall` so that the pipeline is never removed
    let _: &'static _ = Box::leak(Box::new(uninstall));

    // integration with `tracing`
    let telemetry = tracing_opentelemetry::layer().with_tracer(tracer);
    let subscriber = tracing_subscriber::Registry::default().with(telemetry);

    // Make the datadog subscriber the default one throughout the program
    tracing::subscriber::set_global_default(subscriber).unwrap();
}
```
And the `Cargo.toml`:
```toml
[package]
name = "testdatadog"
version = "0.1.0"
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.4.0", features = ["full"] }
opentelemetry = { version = "0.12.0", features = ["tokio-support"] }
opentelemetry-contrib = { version = "0.4.0", features = ["datadog", "reqwest-client"] }
tracing = "0.1.25"
tracing-opentelemetry = "0.11.0"
tracing-subscriber = { version = "0.2.17", features = ["parking_lot"] }
```
When I try to run this I get:
```
❯ RUST_BACKTRACE=1 cargo run
   Compiling testdatadog v0.1.0 (/Users/corentinhenry/Documents/testdatadog)
    Finished dev [unoptimized + debuginfo] target(s) in 3.31s
     Running `target/debug/testdatadog`
thread 'tokio-runtime-worker' panicked at 'A Tokio 1.x context was found, but it is being shutdown.', /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/time/driver/entry.rs:547:13
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/corentinhenry/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: tokio::time::driver::entry::TimerEntry::poll_elapsed
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/time/driver/entry.rs:547:13
   2: tokio::time::driver::sleep::Sleep::poll_elapsed
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/time/driver/sleep.rs:231:9
   3: <tokio::time::driver::sleep::Sleep as core::future::future::Future>::poll
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/time/driver/sleep.rs:251:22
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/corentinhenry/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
   5: tokio::time::interval::Interval::poll_tick
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/time/interval.rs:166:16
   6: <tokio_stream::wrappers::interval::IntervalStream as futures_core::stream::Stream>::poll_next
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-stream-0.1.5/src/wrappers/interval.rs:32:9
   7: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/stream/stream/map.rs:61:26
   8: <futures_util::stream::stream::fuse::Fuse<S> as futures_core::stream::Stream>::poll_next
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/stream/stream/fuse.rs:56:27
   9: futures_util::stream::select::poll_inner
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/stream/select.rs:123:11
  10: <futures_util::stream::select::Select<St1,St2> as futures_core::stream::Stream>::poll_next
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/stream/select.rs:98:13
  11: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.13/src/stream.rs:129:9
  12: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/stream/stream/mod.rs:1415:9
  13: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/stream/stream/next.rs:35:9
  14: opentelemetry::sdk::trace::span_processor::BatchSpanProcessor::new::{{closure}}
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/opentelemetry-0.12.0/src/sdk/trace/span_processor.rs:274:39
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/corentinhenry/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  16: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/corentinhenry/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  17: futures_executor::local_pool::block_on::{{closure}}
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:317:23
  18: futures_executor::local_pool::run_executor::{{closure}}
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:87:37
  19: std::thread::local::LocalKey<T>::try_with
             at /Users/corentinhenry/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  20: std::thread::local::LocalKey<T>::with
             at /Users/corentinhenry/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  21: futures_executor::local_pool::run_executor
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:83:5
  22: futures_executor::local_pool::block_on
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:317:5
  23: opentelemetry::sdk::trace::provider::Builder::with_exporter::{{closure}}::{{closure}}
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/opentelemetry-0.12.0/src/sdk/trace/provider.rs:118:58
  24: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/blocking/task.rs:42:21
  25: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/core.rs:235:17
  26: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/loom/std/unsafe_cell.rs:14:9
  27: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/core.rs:225:13
  28: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/harness.rs:422:23
  29: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/corentinhenry/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  30: std::panicking::try::do_call
             at /Users/corentinhenry/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  31: ___rust_try
  32: std::panicking::try
             at /Users/corentinhenry/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  33: std::panic::catch_unwind
             at /Users/corentinhenry/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  34: tokio::runtime::task::harness::poll_future
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/harness.rs:409:19
  35: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/harness.rs:89:9
  36: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/harness.rs:59:15
  37: tokio::runtime::task::raw::poll
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/raw.rs:104:5
  38: tokio::runtime::task::raw::RawTask::poll
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/raw.rs:66:18
  39: tokio::runtime::task::Notified<S>::run
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/mod.rs:171:9
  40: tokio::runtime::blocking::pool::Inner::run
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/blocking/pool.rs:278:17
  41: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/corentinhenry/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/blocking/pool.rs:258:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by TommyCpp** [comment]
Don't have much time today to dig into the details. But could you try returning the `uninstall` from the `create_datadog_tracing_subscriber` into the main function and see if that solves the problem?

**Comment by little-dude** [comment]
Hey @TommyCpp !

Thank you, your suggestion prevents the crash. However it seems that the traces are still not sent to datadog. I don't see anything in the agent APM log file:

```
❯ tail -f datadog-apm.log
2021-03-26 07:44:50 CET | TRACE | INFO | (pkg/util/log/log.go:526 in func1) | Features detected from environment: map[]
2021-03-26 07:44:50 CET | TRACE | INFO | (pkg/util/log/log.go:526 in func1) | runtime: final GOMAXPROCS value is: 8
2021-03-26 07:44:50 CET | TRACE | INFO | (pkg/util/log/log.go:526 in func1) | Loaded configuration: /opt/datadog-agent/etc/datadog.yaml
2021-03-26 07:44:50 CET | TRACE | INFO | (pkg/trace/agent/run.go:146 in Run) | Trace agent running on host C02DN03VP3YY
2021-03-26 07:44:50 CET | TRACE | INFO | (pkg/trace/api/api.go:153 in Start) | Listening for traces at http://localhost:8126
2021-03-26 07:45:00 CET | TRACE | INFO | (pkg/trace/info/stats.go:101 in LogStats) | No data received
2021-03-26 07:46:00 CET | TRACE | INFO | (pkg/trace/info/stats.go:101 in LogStats) | No data received
```

**Comment by TommyCpp** [comment]
I don't have a datadog key to test it but I think you need to create a span first. You can do it by 
```
let root = span!(tracing::Level::INFO, "app_start", work_units = 2);
let _enter = root.enter();
```
The `error!`, `warn!` marcos don't really create spans for you AFAIK.

**Comment by little-dude** [comment]
Thank a lot @TommyCpp, I'm now seeing a span, with this code:

```rust
#[macro_use]
extern crate tracing;

use opentelemetry_contrib::trace::exporter::datadog;
use tracing_subscriber::layer::SubscriberExt;

#[tokio::main]
async fn main() {
    let _uninstall = create_datadog_tracing_subscriber("http://localhost:8126");
    let root = info_span!("app_start", work_units = 2);
    {
        let _enter = root.enter();
        error!("error");
        warn!("warn");
        info!("info");
        debug!("debug");
        trace!("trace");
    }
}

fn create_datadog_tracing_subscriber(agent: &str) -> datadog::Uninstall {
    let (tracer, uninstall) = datadog::new_pipeline()
        .with_service_name("datadogtest")
        .with_version(datadog::ApiVersion::Version05)
        .with_agent_endpoint(agent)
        .install()
        .unwrap();

    // integration with `tracing`
    let telemetry = tracing_opentelemetry::layer().with_tracer(tracer);
    let subscriber = tracing_subscriber::Registry::default()
        .with(telemetry);

    // Make the datadog subscriber the default one throughout the program
    tracing::subscriber::set_global_default(subscriber).unwrap();

    uninstall
}
```

There are two remaining issues:

1. The span appears as an _error_ span (see this screenshot: ![Screenshot 2021-03-29 at 11 22 30](https://user-images.githubusercontent.com/6646324/112815921-1ad0bb00-9081-11eb-803c-917a49491946.png))
2. Although I enabled log collection in the datadog agent, the logs don't appear in datadog. I can only see the span. `datadog-agent status` shows this:
```
==========
Logs Agent
==========

    Sending compressed logs in HTTPS to agent-http-intake.logs.datadoghq.eu on port 443
    BytesSent: 0
    EncodedBytesSent: 28
    LogsProcessed: 0
    LogsSent: 0

=========
APM Agent
=========
  Status: Running
  Pid: 66890
  Uptime: 604 seconds
  Mem alloc: 17,192,864 bytes
  Hostname: C02DN03VP3YY
  Receiver: localhost:8126
  Endpoints:
    https://trace.agent.datadoghq.eu

  Receiver (previous minute)
  ==========================
    From unknown clients
      Traces received: 1 (195 bytes)
      Spans received: 1

    Default priority sampling rate: 100.0%

  Writer (previous minute)
  ========================
    Traces: 0 payloads, 0 traces, 0 events, 0 bytes
    Stats: 0 payloads, 0 stats buckets, 0 bytes
```
Do I need to do something special in Rust to have the logs forwarded to datadog? It seems that logs [must have three specific attributes (`env`, `version` and `service`) set according to the doc](https://docs.datadoghq.com/tracing/connect_logs_and_traces/). Do I need to do that manually somehow? I'm sorry if these questions are a bit basic, but I'm completely new to open-telemetry and datadog.

**Comment by jtescher** [comment]
If you log at error level in `tracing` it will mark the span an error span via `tracing-opentelemetry`. Should fix the first issue for you. I don't believe that logging is integrated in `opentelemetry-datadog` yet, could open a separate issue for that one
